[package]
name = "negroni"
version = "0.1.0"
authors = ["Jonny Stoten <jonny@jonnystoten.com>"]
edition = "2018"

[dependencies]
bincode = "1.1.4"
serde = { version = "1.0", features = ["derive"] }
dirs = "2.0.1"
